#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port7,  touchLED1,      sensorVexIQ_LED)
#pragma config(Sensor, port8,  bumpSwitchLeft, sensorVexIQ_Touch)
#pragma config(Sensor, port9,  bumpSwitchRight, sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


float display;
float charposx;
float charposy;
float enx ;
float eny ;
float enx1 ;
float eny1 ;
float life ;
float top;
float bottom ;
float top1;
float enx2 ;
float eny2 ;
float enx3 ;
float eny3 ;

task main()
{
	hogCPU();
	top = 10;
	top1 = 15;
	life= 5;
	enx = 120;
	eny = 125;
	enx1 = 120;
	eny1 = 125;


	enx2 = 225;
	eny2 = 250;
	enx3 = 225;
	eny3 = 250;
	charposx = 1;
	charposy = 1;
	repeat(forever) {
		eraseDisplay();
if(getBumperValue(bumpSwitchLeft) == 1 ) {
	charposy -- ;
	writeDebugStream("down");
}

if(getBumperValue(bumpSwitchRight) == 1 ) {
	charposy ++ ;
}
if(enx == 25 && charposy <= top) {
life --;

}

if(enx1 == 25 &&  charposy >= top + 40) {
life --;

}

if(enx2 == 25 &&  charposy <= top1) {
life --;

}

if(enx3 == 25 && charposy >= top1 + 40) {
life --;

}
 string s1 = life; // create the string named s1, "ROBOTC"
  displayTextline(1, "life: %d", life); // display the string, 's1' on line 3


enx1 -- ;
eny1 -- ;

enx -- ;
eny -- ;


enx2 -- ;
eny2 -- ;


enx3 -- ;
eny3 -- ;
eraseCircle(28  , charposy -1, 6);
eraseCircle(28  , charposy +1, 6);
drawRect(enx, top , eny, 1);
//10
fillRect(enx, top, eny, 1);
eraseRect(enx +5, top, eny +8, 1);


drawRect(enx1, top+40, eny1, 30);

fillRect(enx1, top+40, eny1, 30);
eraseRect(enx1 +5, top+40, eny1 +8, 30);
//drawRect(Left, Top, Right, Bottom);
if(enx <= 0) {
enx = 120;
eny = 125;
top = random[20];
}
if(enx1 <= 0) {
enx1 = 120;
eny1 = 125;
}

if(enx2 <= 0) {
enx2 = 225;
eny2 = 250;

top1 = random[20];
}
if(enx3 <= 0) {
enx3 = 225;
eny3 = 250;
}



//second colum
drawRect(enx2, top1 , eny2, 1);
//10
fillRect(enx2, top1, eny2, 1);
eraseRect(enx2 +5, top1, eny2 +8, 1);


drawRect(enx3, top1+40, eny3, 30);

fillRect(enx3, top1+40, eny3, 30);
eraseRect(enx3 +5, top1+40, eny3 +8, 30);
//drawRect(Left, Top, Right, Bottom);
if(enx <= 0) {
enx = 120;
eny = 125;
top = random[20];
}
if(enx1 <= 0) {
enx1 = 120;
eny1 = 125;
}


if(charposy > 5 && getBumperValue(bumpSwitchRight) <= 0) {
	charposy -- ;

}

drawCircle(28, charposy, 5);
sleep(100);


if(life == 0) {
repeat(forever) {
eraseDisplay();
displayCenteredBigTextLine(3, "GAME OVER");

}
}
}

}
